const fs=require('fs'),path=require('path');
const configFile=path.join(__dirname,'weather-config.json');
let locationPending=null,feedPending=null,feedCache=null,retryAt=0;
const readings=new Map();
function readConfig(){try{return JSON.parse(fs.readFileSync(configFile,'utf8'));}catch{return {mode:'auto'};}}
function validLocation(c){return typeof c.latitude==='number'&&Number.isFinite(c.latitude)&&Math.abs(c.latitude)<=90&&typeof c.longitude==='number'&&Number.isFinite(c.longitude)&&Math.abs(c.longitude)<=180;}
async function json(url){const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Gegevensdienst niet bereikbaar');return r.json();}
async function location(){
 const c=readConfig();if(validLocation(c))return c;if(Date.now()<retryAt)throw Error('Locatie tijdelijk niet beschikbaar');
 if(!locationPending)locationPending=(async()=>{const d=await json('https://ipwho.is/');if(!d.success||!validLocation(d))throw Error('Locatie niet gevonden');const found={mode:'auto',name:String(d.city||d.region||'Automatische locatie'),latitude:d.latitude,longitude:d.longitude,detectedAt:new Date().toISOString()};if(readConfig().mode!=='manual')fs.writeFileSync(configFile,JSON.stringify(found,null,2));return readConfig();})();
 try{return await locationPending;}catch(e){retryAt=Date.now()+60000;throw e;}finally{locationPending=null;}
}
function stations(state){const drivers=state.deviceDrivers||[];return (state.genericDevices||[]).filter(d=>{const driver=drivers.find(x=>x.id===d.driverId)||{};return [d.type,driver.category,driver.baseType].some(x=>['weather','weatherstation','weather-station'].includes(String(x).toLowerCase()));}).map(d=>({id:String(d.id),name:d.name||'KNX weerstation',ga:String(d.outdoorTemperatureGa||d.temperatureGa||d.measuredGa||d.parameters?.outdoorTemperatureGa||d.parameters?.temperatureGa||'').trim()}));}
function record(ga,value){if(typeof value==='number'&&Number.isFinite(value)&&value>=-80&&value<=80)readings.set(ga,{temperature:value,updatedAt:new Date().toISOString()});}
function knxWeather(state,connected){const list=stations(state);if(!list.length)return null;const s=list.find(s=>s.ga&&readings.has(s.ga))||list[0],r=readings.get(s.ga),fresh=connected&&r&&Date.now()-Date.parse(r.updatedAt)<3600000;return {configured:true,source:'knx',station:s.name,temperature:fresh?r.temperature:null,updatedAt:fresh?r.updatedAt:null,status:fresh?'ok':connected?'waiting':'offline'};}
async function feed(){if(feedCache&&Date.now()-feedCache.time<300000)return feedCache.data;if(!feedPending)feedPending=json('https://data.buienradar.nl/2.0/feed/json').then(data=>{feedCache={time:Date.now(),data};return data;});try{return await feedPending;}finally{feedPending=null;}}
function distance(a,b){const rad=x=>x*Math.PI/180,x=rad(b.lat-a.latitude),y=rad(b.lon-a.longitude),q=Math.sin(x/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.lat))*Math.sin(y/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function measuredAt(value){if(/Z$|[+-]\d\d:\d\d$/.test(value))return new Date(value).toISOString();const hint=new Date(value+'Z'),zone=new Intl.DateTimeFormat('en',{timeZone:'Europe/Amsterdam',timeZoneName:'shortOffset'}).formatToParts(hint).find(p=>p.type==='timeZoneName').value;return new Date(hint.getTime()-Number(zone.replace('GMT',''))*3600000).toISOString();}
async function getWeather(state,connected){const own=knxWeather(state,connected);if(own)return {...own,location:readConfig().name||''};const loc=await location(),data=await feed(),all=(data.actual?.stationmeasurements||[]).filter(s=>typeof s.temperature==='number'&&Number.isFinite(s.temperature)&&Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&s.timestamp);all.sort((a,b)=>distance(loc,a)-distance(loc,b));const s=all[0];if(!s)throw Error('Geen temperatuur beschikbaar');const km=distance(loc,s);if(km>150)throw Error('Geen Buienradar-meetstation nabij deze locatie');const updatedAt=measuredAt(s.timestamp);if(Date.now()-Date.parse(updatedAt)>3600000)throw Error('Weergegevens verouderd');return {configured:true,source:'buienradar',temperature:s.temperature,location:loc.name,station:s.stationname,distanceKm:Math.round(km),updatedAt,status:'ok'};}
async function settings(state){let error='';try{await location();}catch(e){error=e.message;}return {...readConfig(),error,source:stations(state).length?'knx':'buienradar',station:stations(state)[0]?.name||''};}
async function save(input){if(input.mode==='auto'){fs.writeFileSync(configFile,JSON.stringify({mode:'auto'}));retryAt=0;return location();}const name=String(input.name||'').trim();if(name.length<2||name.length>120)throw Error('Vul een plaatsnaam in');const url=new URL('https://geocoding-api.open-meteo.com/v1/search');url.search=new URLSearchParams({name,count:'8',language:'nl'}).toString();const d=await json(url),list=(d.results||[]).filter(validLocation);if(!input.locationId)return {candidates:list.map(c=>({id:c.id,name:[c.name,c.admin1,c.country].filter(Boolean).join(', ')}))};const c=list.find(c=>String(c.id)===String(input.locationId));if(!c)throw Error('Kies een gevonden plaats');const config={mode:'manual',name:[c.name,c.admin1,c.country].filter(Boolean).join(', '),latitude:c.latitude,longitude:c.longitude};fs.writeFileSync(configFile,JSON.stringify(config,null,2));return config;}
module.exports={getWeather,settings,save,stations,record,knxWeather,distance,measuredAt};
