'use strict';
let csrf='',systems=[],allowedMacs=[],timer;
const events={'portal.relay_unavailable':'Inloggen mislukt: remote verbinding ontbreekt','portal.profile_unavailable':'Accountverificatie niet beschikbaar','portal.password_mismatch':'Inloggen geweigerd door wachtwoordcontrole','portal.relay_error':'Remote systeem reageert niet','portal.login':'Gebruiker via cloud ingelogd','portal.login_failed':'Cloudlogin geweigerd','system.auto_registered':'Systeem automatisch geregistreerd','admin.login':'Beheerder ingelogd','admin.login_failed':'Beheerlogin geweigerd','admin.logout':'Beheerder uitgelogd','pairing.created':'Koppelcode aangemaakt','system.registered':'Systeem geregistreerd','system.deleted':'Ingetrokken systeem verwijderd','system.revoked':'Cloudtoegang ingetrokken','system.disabled':'Cloudtoegang uitgezet vanuit Nuvex','system.accounts_updated':'Accountlijst bijgewerkt','system.reconnected':'Systeem opnieuw verbonden','system.mac_denied':'Niet toegestaan MAC-adres geweigerd','system.mac_mismatch':'Afwijkend MAC-adres geweigerd','mac.allowed':'MAC-adres toegestaan','mac.removed':'MAC-adres verwijderd','relay.connected':'Cloudrelay verbonden','relay.disconnected':'Cloudrelay verbroken','portal.system_selected':'Systeem gekozen'};
const $=id=>document.getElementById(id);
async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});const result=await response.json();if(!response.ok){if(response.status===401)showLogin();throw Error(result.error||'Verzoek mislukt.');}return result;}
function message(error){$('message').textContent=error.message||error;}
function showLogin(){clearInterval(timer);csrf='';$('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('systems').replaceChildren();$('audit').replaceChildren();$('pairing').replaceChildren();$('pairing').hidden=true;systems=[];allowedMacs=[];}
function element(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
function renderSystems(){const filter=$('search').value.toLowerCase();$('systems').replaceChildren();for(const s of systems.filter(s=>JSON.stringify([s.name,s.first_email,s.admin_email,s.accounts,s.ip_address,s.mac_address,s.location]).toLowerCase().includes(filter))){const card=element('article','','system'),head=element('div','','system-head');head.append(element('h2',s.name||'Naam ontbreekt'),element('span',s.revoked?'Ingetrokken':s.online?'● Online':'○ Offline',s.online?'badge':'badge offline'));card.append(head);if(typeof s.remoteConnected==='boolean')card.append(element('p',s.remoteConnected?'Remote verbinding actief':'Geen remote verbinding'));if(s.enrollment==='automatic')card.append(element('p','Automatisch geregistreerd'));const identity=element('div','','system-location');identity.append(element('span','🌐 '+(s.ip_address||'IP onbekend')),element('span','▦ '+(s.mac_address||'MAC onbekend')),element('span','⌖ '+(s.location||'Locatie onbekend')));card.append(identity);const details=element('div','','details');for(const [label,value]of [['Eerst geregistreerd',s.first_email],['Huidige admin',s.admin_email],['Laatst verbonden',new Date(s.seen*1000).toLocaleString('nl-NL')]]){const cell=element('div');cell.append(element('small',label),element('span',value));details.append(cell);}card.append(details);const list=element('details'),ul=element('ul');list.append(element('summary',`${s.accounts.length} accounts · ${s.version||'Versie onbekend'}`));for(const account of s.accounts)ul.append(element('li',`${account.email} · ${account.role}${account.disabled?' · Uitgeschakeld':''}`));list.append(ul);card.append(list);const action=element('button',s.revoked?'Verwijderen':'Toegang intrekken','revoke');action.onclick=async()=>{const text=s.revoked?`Ingetrokken systeem ${s.name} definitief verwijderen?`:`Cloudtoegang voor ${s.name} intrekken?`;if(!confirm(text))return;try{await api(s.revoked?'/api/delete-system':'/api/revoke',{id:s.id});await refresh();}catch(e){message(e);}};card.append(action);$('systems').append(card);}if(!$('systems').children.length)$('systems').append(element('p','Geen systemen gevonden. Voeg eerst het MAC-adres toe en koppel daarna de Nuvex-server.'));}
function renderMacs(){const box=$('macList');box.replaceChildren();$('macCount').textContent=allowedMacs.length+' toegestaan';for(const item of allowedMacs){const row=element('div','','mac-row');row.append(element('code',item.mac),element('span',item.label||'Zonder naam'));const remove=element('button','Verwijderen');remove.onclick=async()=>{if(!confirm(`${item.mac} uit de toelatingslijst verwijderen? De cloudrelay van dit systeem wordt daarna geweigerd.`))return;try{await api('/api/allowed-macs/remove',{mac:item.mac});await refresh();}catch(e){message(e);}};row.append(remove);box.append(row);}if(!allowedMacs.length)box.append(element('p','Nog geen MAC-adressen toegestaan. Registratie en cloudrelay worden geblokkeerd.'));}
function renderAudit(rows){$('audit').replaceChildren(...rows.map(a=>{const row=element('div','','audit-row');row.append(element('span',new Date(a.at*1000).toLocaleString('nl-NL')),element('span',(events[a.event]||a.event)+(a.system_name?' · '+a.system_name:a.detail?' · '+a.detail:'')),element('code',a.ip_address||'IP —'),element('code',a.effective_mac||a.mac_address||'MAC —'));return row;}));}
function renderHealth(status,tunnel){const active=systems.filter(s=>!s.revoked),missingMac=active.some(s=>!s.mac_address||!allowedMacs.some(m=>m.mac===s.mac_address)),offline=active.filter(s=>!s.online||s.remoteConnected===false);let level='green',title='Alles werkt correct',text='Cloudserver, toelatingslijst en geregistreerde systemen zijn operationeel.';if(!allowedMacs.length||missingMac||!status.remoteAccessEnabled){level='red';title='Actie vereist';text=!allowedMacs.length?'Voeg minimaal één toegestaan MAC-adres toe. Registratie en relay zijn nu geblokkeerd.':missingMac?'Een geregistreerd systeem heeft geen toegestaan MAC-adres.':'Remote cloudtoegang is niet actief.';}else if(!active.length||offline.length||tunnel.error){level='orange';title='Aandacht vereist';text=tunnel.error||(!active.length?'Er zijn nog geen actieve systemen geregistreerd.':`${offline.length} systeem of systemen zijn offline of hebben geen relayverbinding.`);}$('health').dataset.level=level;$('healthTitle').textContent=title;$('healthText').textContent=text;}
async function refresh(){const [systemData,audit,macs,status,tunnel]=await Promise.all([api('/api/systems'),api('/api/audit'),api('/api/allowed-macs'),api('/api/status'),api('/api/tunnel')]);systems=systemData;allowedMacs=macs;$('total').textContent=systems.length;$('online').textContent=systems.filter(s=>s.online).length;$('remoteStatus').textContent=status.remoteAccessEnabled?'Beschikbaar':'Niet actief';renderSystems();renderMacs();renderAudit(audit);renderTunnel(tunnel);renderHealth(status,tunnel);let panel=$('serverStatus');if(!panel){panel=element('p');panel.id='serverStatus';$('dashboard').prepend(panel);}panel.textContent=`Cloudserver v${status.version} · Actief sinds ${Math.floor(status.uptimeSeconds/60)} minuten · Bijgewerkt ${new Date(status.serverTime*1000).toLocaleTimeString('nl-NL')}`;$('message').textContent='';}
async function dashboard(){$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('message').textContent='';await refresh();clearInterval(timer);timer=setInterval(()=>refresh().catch(message),15000);}
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));csrf=(await api('/api/login',data)).csrf;e.target.reset();await dashboard();}catch(e){message(e);}finally{button.disabled=false;}};
$('logout').onclick=async()=>{try{await api('/api/logout',{});showLogin();}catch(e){message(e);}};
$('pair').onclick=async()=>{try{const p=await api('/api/pairing',{});$('pairing').replaceChildren(element('strong','Eenmalige koppelcode'),element('code',p.code),element('p',`Voer deze code lokaal in Nuvex in. Geldig tot ${new Date(p.expires*1000).toLocaleTimeString('nl-NL')}.`));$('pairing').hidden=false;}catch(e){message(e);}};
$('macForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/allowed-macs/add',Object.fromEntries(new FormData(e.target)));e.target.reset();await refresh();}catch(error){message(error);}finally{button.disabled=false;}};
$('search').oninput=renderSystems;
api('/api/session').then(async s=>{csrf=s.csrf;await dashboard();}).catch(()=>showLogin());
function renderTunnel(t){$('tunnelStart').disabled=t.running;$('tunnelStop').disabled=!t.running;$('tunnelStatus').textContent=t.error||(t.connected?'Tunnel verbonden':t.running?'Tunnel wordt gestart…':'Tunnel uitgeschakeld');$('tunnelUrl').hidden=!t.url;$('tunnelUrl').textContent=t.url;if(t.url)$('tunnelUrl').href=t.url;else $('tunnelUrl').removeAttribute('href');}
async function refreshTunnel(){const tunnel=await api('/api/tunnel');renderTunnel(tunnel);return tunnel;}
for(const [id,action]of[['tunnelStart','start'],['tunnelStop','stop']])$(id).onclick=async()=>{const b=$(id);b.disabled=true;try{renderTunnel(await api('/api/tunnel/'+action,{}));await refresh();}catch(e){message(e);b.disabled=false;}};
$('tunnelForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{renderTunnel(await api('/api/tunnel/configure',Object.fromEntries(new FormData(e.target))));e.target.reset();await refresh();}catch(err){message(err);}finally{b.disabled=false;}};
$('tunnelFixed').onclick=async()=>{try{renderTunnel(await api('/api/tunnel/start',{mode:'fixed'}));await refresh();}catch(e){message(e);}};
$('tunnelRemove').onclick=async()=>{if(!confirm('Tunnel stoppen en het opgeslagen token verwijderen?'))return;try{renderTunnel(await api('/api/tunnel/remove',{}));await refresh();}catch(e){message(e);}};
