let csrf='', systems=[], timer;
const events={'portal.relay_unavailable':'Inloggen mislukt: remote verbinding ontbreekt','portal.profile_unavailable':'Inloggen mislukt: Nuvex-accountverificatie niet beschikbaar','portal.password_mismatch':'Inloggen geweigerd door wachtwoordcontrole','portal.relay_error':'Inloggen mislukt: remote systeem reageert niet','system.auto_registered':'Systeem automatisch geregistreerd','admin.login':'Beheerder ingelogd','admin.login_failed':'Inlogpoging geweigerd','admin.logout':'Beheerder uitgelogd','pairing.created':'Koppelcode aangemaakt','system.registered':'Systeem geregistreerd','system.deleted':'Ingetrokken systeem verwijderd','system.revoked':'Cloudtoegang ingetrokken','system.disabled':'Cloudtoegang uitgezet vanuit Nuvex','system.accounts_updated':'Accountlijst bijgewerkt','system.reconnected':'Systeem opnieuw verbonden'};
const $=id=>document.getElementById(id);
async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok){if(response.status===401)showLogin();throw Error(result.error||'Verzoek mislukt.');}return result;}
function message(error){$('message').textContent=error.message||error;}
function showLogin(){clearInterval(timer);csrf='';$('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('systems').replaceChildren();$('audit').replaceChildren();$('pairing').replaceChildren();$('pairing').hidden=true;systems=[];}
function element(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
function render(){const filter=$('search').value.toLowerCase();$('systems').replaceChildren();for(const s of systems.filter(s=>JSON.stringify([s.name,s.first_email,s.admin_email,s.accounts]).toLowerCase().includes(filter))){const card=element('article','','system'), head=element('div','','system-head');head.append(element('h2',s.name),element('span',s.revoked?'Ingetrokken':s.online?'● Online':'○ Offline',s.online?'badge':'badge offline'));card.append(head);if(typeof s.remoteConnected==='boolean')card.append(element('p',s.remoteConnected?'Remote verbinding actief':'Geen remote verbinding · registratie alleen geeft nog geen browsertoegang'));if(s.enrollment==='automatic')card.append(element('p','Automatisch geregistreerd · e-mailidentiteit niet geverifieerd'));const details=element('div','','details');for(const [label,value]of [['Eerst geregistreerd',s.first_email],['Huidige admin',s.admin_email],['Laatst verbonden',new Date(s.seen*1000).toLocaleString('nl-NL')]]){const cell=element('div');cell.append(element('small',label),element('span',value));details.append(cell);}card.append(details);const list=element('details'), ul=element('ul');list.append(element('summary',`${s.accounts.length} geregistreerde accounts · ${s.version||'Versie onbekend'}`));for(const account of s.accounts)ul.append(element('li',`${account.email} · ${account.role}${account.disabled?' · Uitgeschakeld':''}`));list.append(ul);card.append(list);if(!s.revoked){const revoke=element('button','Toegang intrekken','revoke');revoke.onclick=async()=>{if(!confirm(`Cloudtoegang voor ${s.name} intrekken? Opnieuw koppelen is daarna nodig.`))return;try{await api('/api/revoke',{id:s.id});await refresh();}catch(e){message(e);}};card.append(revoke);}else{const remove=element('button','Verwijderen','revoke');remove.onclick=async()=>{if(!confirm(`Ingetrokken systeem ${s.name} en de bijbehorende accountgegevens verwijderen?`))return;try{await api('/api/delete-system',{id:s.id});await refresh();}catch(e){message(e);}};card.append(remove);}$('systems').append(card);}if(!$('systems').children.length)$('systems').append(element('p','Geen systemen gevonden. Koppel een Nuvex-systeem om te beginnen.'));}
async function refresh(){systems=await api('/api/systems');$('total').textContent=systems.length;$('online').textContent=systems.filter(s=>s.online).length;render();const audit=await api('/api/audit');$('audit').replaceChildren(...audit.map(a=>element('div',`${new Date(a.at*1000).toLocaleString('nl-NL')} · ${events[a.event]||a.event}${a.system_id?' · '+a.system_id:''}`)));await refreshTunnel();const status=await api('/api/status');$('remoteStatus').textContent=status.remoteAccessEnabled?'Beschikbaar':'In voorbereiding';let panel=$('serverStatus');if(!panel){panel=element('p');panel.id='serverStatus';$('dashboard').prepend(panel);}panel.textContent=`Cloudserver v${status.version} · Actief sinds ${Math.floor(status.uptimeSeconds/60)} minuten · Bijgewerkt ${new Date(status.serverTime*1000).toLocaleTimeString('nl-NL')}`;$('message').textContent='';}
async function dashboard(){ $('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('message').textContent='';await refresh();clearInterval(timer);timer=setInterval(()=>refresh().catch(message),15000);}
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));csrf=(await api('/api/login',data)).csrf;e.target.reset();await dashboard();}catch(e){message(e);}finally{button.disabled=false;}};
$('logout').onclick=async()=>{try{await api('/api/logout',{});showLogin();}catch(e){message(e);}};
$('pair').onclick=async()=>{try{const p=await api('/api/pairing',{});$('pairing').replaceChildren(element('strong','Eenmalige koppelcode'),element('code',p.code),element('p',`Voer deze code lokaal in Nuvex in. Geldig tot ${new Date(p.expires*1000).toLocaleTimeString('nl-NL')}. Behandel de code als een wachtwoord.`));$('pairing').hidden=false;}catch(e){message(e);}};
$('search').oninput=render;
api('/api/session').then(async s=>{csrf=s.csrf;await dashboard();}).catch(()=>showLogin());

function renderTunnel(t){$('tunnelStart').disabled=t.running;$('tunnelStop').disabled=!t.running;$('tunnelStatus').textContent=t.error||(t.connected?'Tunnel verbonden':t.running?'Tunnel wordt gestart…':'Tunnel uitgeschakeld');$('tunnelUrl').hidden=!t.url;$('tunnelUrl').textContent=t.url;if(t.url)$('tunnelUrl').href=t.url;else $('tunnelUrl').removeAttribute('href');}
async function refreshTunnel(){renderTunnel(await api('/api/tunnel'));}
for(const [id,action] of [['tunnelStart','start'],['tunnelStop','stop']])$(id).onclick=async()=>{const b=$(id);b.disabled=true;try{renderTunnel(await api('/api/tunnel/'+action,{}));}catch(e){message(e);b.disabled=false;}};

$('tunnelForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{renderTunnel(await api('/api/tunnel/configure',Object.fromEntries(new FormData(e.target))));e.target.reset();}catch(err){message(err);}finally{b.disabled=false;}};
$('tunnelFixed').onclick=async()=>{try{renderTunnel(await api('/api/tunnel/start',{mode:'fixed'}));}catch(e){message(e);}};
$('tunnelRemove').onclick=async()=>{if(!confirm('Tunnel stoppen en het opgeslagen token verwijderen?'))return;try{renderTunnel(await api('/api/tunnel/remove',{}));}catch(e){message(e);}};
